### ISSUE TITLE
Die programm kann nicht run

### ISSUE THREAD

**Issue by KRIShark** [Toeller/HHBK_Chemicals#67]
Severity	Code	Description	Project	File	Line	Suppression State
Error		Resource file "Properties\Resources.resx" cannot be found.	HHBK_Chemicals_ERP_CS			

Ist das nur in meine clon so?
was wäre das lösung daführ?

**Comment by Toeller** [comment]
Ist erledigt. Die fehlenden resourcen Dateien sind jetzt da und die Fehler behoben.

**Comment by Toeller** [comment]
Bitte neu pullen
